/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as SolutionsIndustryRouteImport } from './routes/solutions.$industry'
import { Route as ServicesWorkflowAutomationRouteImport } from './routes/services.workflow-automation'
import { Route as ServicesVoiceAiRouteImport } from './routes/services.voice-ai'
import { Route as ServicesLeadGenerationRouteImport } from './routes/services.lead-generation'
import { Route as ServicesCustomerSupportRouteImport } from './routes/services.customer-support'
import { Route as ServicesCrmIntegrationRouteImport } from './routes/services.crm-integration'
import { Route as ServicesAiChatbotsRouteImport } from './routes/services.ai-chatbots'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const SolutionsIndustryRoute = SolutionsIndustryRouteImport.update({
  id: '/$industry',
  path: '/$industry',
  getParentRoute: () => SolutionsRoute,
} as any)
const ServicesWorkflowAutomationRoute =
  ServicesWorkflowAutomationRouteImport.update({
    id: '/workflow-automation',
    path: '/workflow-automation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesVoiceAiRoute = ServicesVoiceAiRouteImport.update({
  id: '/voice-ai',
  path: '/voice-ai',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLeadGenerationRoute = ServicesLeadGenerationRouteImport.update({
  id: '/lead-generation',
  path: '/lead-generation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomerSupportRoute = ServicesCustomerSupportRouteImport.update({
  id: '/customer-support',
  path: '/customer-support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCrmIntegrationRoute = ServicesCrmIntegrationRouteImport.update({
  id: '/crm-integration',
  path: '/crm-integration',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiChatbotsRoute = ServicesAiChatbotsRouteImport.update({
  id: '/ai-chatbots',
  path: '/ai-chatbots',
  getParentRoute: () => ServicesRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services/ai-chatbots': typeof ServicesAiChatbotsRoute
  '/services/crm-integration': typeof ServicesCrmIntegrationRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/voice-ai': typeof ServicesVoiceAiRoute
  '/services/workflow-automation': typeof ServicesWorkflowAutomationRoute
  '/solutions/$industry': typeof SolutionsIndustryRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services/ai-chatbots': typeof ServicesAiChatbotsRoute
  '/services/crm-integration': typeof ServicesCrmIntegrationRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/voice-ai': typeof ServicesVoiceAiRoute
  '/services/workflow-automation': typeof ServicesWorkflowAutomationRoute
  '/solutions/$industry': typeof SolutionsIndustryRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/services/ai-chatbots': typeof ServicesAiChatbotsRoute
  '/services/crm-integration': typeof ServicesCrmIntegrationRoute
  '/services/customer-support': typeof ServicesCustomerSupportRoute
  '/services/lead-generation': typeof ServicesLeadGenerationRoute
  '/services/voice-ai': typeof ServicesVoiceAiRoute
  '/services/workflow-automation': typeof ServicesWorkflowAutomationRoute
  '/solutions/$industry': typeof SolutionsIndustryRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book-demo'
    | '/contact'
    | '/demo'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/solutions'
    | '/terms'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/services/ai-chatbots'
    | '/services/crm-integration'
    | '/services/customer-support'
    | '/services/lead-generation'
    | '/services/voice-ai'
    | '/services/workflow-automation'
    | '/solutions/$industry'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book-demo'
    | '/contact'
    | '/demo'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/solutions'
    | '/terms'
    | '/dashboard'
    | '/history'
    | '/profile'
    | '/services/ai-chatbots'
    | '/services/crm-integration'
    | '/services/customer-support'
    | '/services/lead-generation'
    | '/services/voice-ai'
    | '/services/workflow-automation'
    | '/solutions/$industry'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book-demo'
    | '/contact'
    | '/demo'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/solutions'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/services/ai-chatbots'
    | '/services/crm-integration'
    | '/services/customer-support'
    | '/services/lead-generation'
    | '/services/voice-ai'
    | '/services/workflow-automation'
    | '/solutions/$industry'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookDemoRoute: typeof BookDemoRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/solutions/$industry': {
      id: '/solutions/$industry'
      path: '/$industry'
      fullPath: '/solutions/$industry'
      preLoaderRoute: typeof SolutionsIndustryRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/services/workflow-automation': {
      id: '/services/workflow-automation'
      path: '/workflow-automation'
      fullPath: '/services/workflow-automation'
      preLoaderRoute: typeof ServicesWorkflowAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/voice-ai': {
      id: '/services/voice-ai'
      path: '/voice-ai'
      fullPath: '/services/voice-ai'
      preLoaderRoute: typeof ServicesVoiceAiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/lead-generation': {
      id: '/services/lead-generation'
      path: '/lead-generation'
      fullPath: '/services/lead-generation'
      preLoaderRoute: typeof ServicesLeadGenerationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/customer-support': {
      id: '/services/customer-support'
      path: '/customer-support'
      fullPath: '/services/customer-support'
      preLoaderRoute: typeof ServicesCustomerSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/crm-integration': {
      id: '/services/crm-integration'
      path: '/crm-integration'
      fullPath: '/services/crm-integration'
      preLoaderRoute: typeof ServicesCrmIntegrationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-chatbots': {
      id: '/services/ai-chatbots'
      path: '/ai-chatbots'
      fullPath: '/services/ai-chatbots'
      preLoaderRoute: typeof ServicesAiChatbotsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServicesRouteChildren {
  ServicesAiChatbotsRoute: typeof ServicesAiChatbotsRoute
  ServicesCrmIntegrationRoute: typeof ServicesCrmIntegrationRoute
  ServicesCustomerSupportRoute: typeof ServicesCustomerSupportRoute
  ServicesLeadGenerationRoute: typeof ServicesLeadGenerationRoute
  ServicesVoiceAiRoute: typeof ServicesVoiceAiRoute
  ServicesWorkflowAutomationRoute: typeof ServicesWorkflowAutomationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAiChatbotsRoute: ServicesAiChatbotsRoute,
  ServicesCrmIntegrationRoute: ServicesCrmIntegrationRoute,
  ServicesCustomerSupportRoute: ServicesCustomerSupportRoute,
  ServicesLeadGenerationRoute: ServicesLeadGenerationRoute,
  ServicesVoiceAiRoute: ServicesVoiceAiRoute,
  ServicesWorkflowAutomationRoute: ServicesWorkflowAutomationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsIndustryRoute: typeof SolutionsIndustryRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsIndustryRoute: SolutionsIndustryRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookDemoRoute: BookDemoRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
